package com.thecode.aestheticdialogs

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.github.takahirom.roborazzi.ExperimentalRoborazziApi
import com.github.takahirom.roborazzi.captureScreenRoboImage
import com.thecode.aestheticdialogs.components.notification.AestheticNotification
import com.thecode.aestheticdialogs.components.notification.models.NotificationUiModel
import com.thecode.aestheticdialogs.foundation.AestheticDialogsTheme
import com.thecode.aestheticdialogs.foundation.DialogTone
import com.thecode.aestheticdialogs.tokens.AestheticPalette
import com.thecode.aestheticdialogs.tokens.AestheticSpacing
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode

/**
 * Draws the README header image.
 *
 * The banner is composed out of the library's own tokens and its own notification
 * component rather than exported from a design tool, which keeps one promise the
 * project makes to itself: if the palette changes, the picture at the top of the
 * README changes with it. It is regenerated by `scripts/generate-docs-images.sh`
 * along with everything else in `docs/images`.
 *
 * One banner per status tone, so the header doubles as the palette: success,
 * info, warning, error.
 */
@RunWith(AndroidJUnit4::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@Config(qualifiers = "w1200dp-h480dp-mdpi")
@OptIn(ExperimentalRoborazziApi::class)
class DocsHeroImageTest {

    @get:Rule
    val composeRule = createComposeRule()

    @Test
    fun heroBanner() {
        composeRule.setContent {
            AestheticDialogsTheme(darkTheme = false) {
                Row(
                    modifier = Modifier
                        .fillMaxSize()
                        .background(backdrop())
                        .padding(horizontal = HERO_GUTTER, vertical = AestheticSpacing.xxxl),
                    verticalAlignment = Alignment.CenterVertically,
                ) {
                    Wordmark(Modifier.weight(WORDMARK_WEIGHT))
                    Spacer(Modifier.width(HERO_GUTTER))
                    BannerStack(Modifier.weight(STACK_WEIGHT))
                }
            }
        }
        captureScreenRoboImage("$DOCS_IMAGES/banner.png")
    }

    /** A diagonal wash from the light canvas into a faint tint of the info accent. */
    private fun backdrop(): Brush = Brush.linearGradient(
        0.0f to AestheticPalette.White,
        0.5f to AestheticPalette.Grey50,
        1.0f to AestheticPalette.BlueTintLight,
        start = Offset.Zero,
        end = Offset(BACKDROP_SPAN, BACKDROP_SPAN),
    )

    @Composable
    private fun Wordmark(modifier: Modifier) {
        val colors = AestheticDialogsTheme.colors
        Column(
            modifier = modifier.fillMaxHeight(),
            verticalArrangement = Arrangement.Center,
        ) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text(
                    text = "Aesthetic",
                    style = TextStyle(
                        fontSize = TITLE_SIZE,
                        fontWeight = FontWeight.Light,
                        color = colors.content.primary,
                    ),
                )
                Text(
                    text = "Dialogs",
                    style = TextStyle(
                        fontSize = TITLE_SIZE,
                        fontWeight = FontWeight.Bold,
                        color = colors.content.primary,
                    ),
                )
            }

            Spacer(Modifier.height(AestheticSpacing.xl))

            Text(
                text = "A Jetpack Compose dialog design system.",
                style = TextStyle(fontSize = TAGLINE_SIZE, color = colors.content.secondary),
            )
            Spacer(Modifier.height(AestheticSpacing.sm))
            Text(
                text = "Component → Variant → Primitive → Tokens",
                style = TextStyle(fontSize = SUBTAGLINE_SIZE, color = colors.content.muted),
            )
        }
    }

    /** Four real banners, rendered by the real component: one per status tone. */
    @Composable
    private fun BannerStack(modifier: Modifier) {
        Column(
            modifier = modifier,
            verticalArrangement = Arrangement.spacedBy(AestheticSpacing.md),
        ) {
            AestheticNotification(
                uiModel = NotificationUiModel.Default(
                    title = "Saved",
                    message = "Your changes are on every device.",
                    tone = DialogTone.Success,
                ),
                onDismiss = {},
            )
            AestheticNotification(
                uiModel = NotificationUiModel.Filled(
                    title = "Seven dialog families",
                    message = "One frame, one theme, one set of guarantees.",
                    tone = DialogTone.Info,
                ),
                onDismiss = {},
            )
            AestheticNotification(
                uiModel = NotificationUiModel.Ambient(
                    title = "You are offline",
                    message = "We will sync as soon as you reconnect.",
                    tone = DialogTone.Warning,
                ),
                onDismiss = {},
            )
            AestheticNotification(
                uiModel = NotificationUiModel.Gradient(
                    title = "Payment declined",
                    message = "Your bank refused the charge.",
                    timestamp = "13:56",
                    tone = DialogTone.Error,
                ),
                onDismiss = {},
            )
        }
    }

    private companion object {
        const val DOCS_IMAGES = "../docs/images"

        val HERO_GUTTER = 56.dp
        const val WORDMARK_WEIGHT = 1.05f
        const val STACK_WEIGHT = 1f

        val TITLE_SIZE = 54.sp
        val TAGLINE_SIZE = 20.sp
        val SUBTAGLINE_SIZE = 15.sp

        const val BACKDROP_SPAN = 1400f
    }
}
