package com.thecode.aestheticdialogs

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.layout.wrapContentHeight
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.unit.dp
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.github.takahirom.roborazzi.ExperimentalRoborazziApi
import com.github.takahirom.roborazzi.RoborazziOptions
import com.github.takahirom.roborazzi.captureRoboImage
import com.github.takahirom.roborazzi.captureScreenRoboImage
import com.thecode.aestheticdialogs.components.alert.AestheticAlertDialog
import com.thecode.aestheticdialogs.components.alert.models.AlertDialogUiModel
import com.thecode.aestheticdialogs.components.confirmation.AestheticConfirmationDialog
import com.thecode.aestheticdialogs.components.confirmation.models.ConfirmationDialogUiModel
import com.thecode.aestheticdialogs.components.content.AestheticContentDialog
import com.thecode.aestheticdialogs.components.content.models.ContentDialogUiModel
import com.thecode.aestheticdialogs.components.feedback.AestheticFeedbackDialog
import com.thecode.aestheticdialogs.components.feedback.models.FeedbackDialogUiModel
import com.thecode.aestheticdialogs.components.header.AestheticHeaderDialog
import com.thecode.aestheticdialogs.components.header.models.HeaderDialogUiModel
import com.thecode.aestheticdialogs.components.input.AestheticInputDialog
import com.thecode.aestheticdialogs.components.input.models.InputDialogUiModel
import com.thecode.aestheticdialogs.components.notification.AestheticNotification
import com.thecode.aestheticdialogs.components.notification.models.NotificationAction
import com.thecode.aestheticdialogs.components.notification.models.NotificationPresence
import com.thecode.aestheticdialogs.components.notification.models.NotificationUiModel
import com.thecode.aestheticdialogs.components.progress.AestheticProgressDialog
import com.thecode.aestheticdialogs.components.progress.models.ProgressDialogUiModel
import com.thecode.aestheticdialogs.components.selection.AestheticSelectionDialog
import com.thecode.aestheticdialogs.components.selection.models.SelectionDialogUiModel
import com.thecode.aestheticdialogs.components.selection.models.SelectionItem
import com.thecode.aestheticdialogs.components.sheet.AestheticSheetDialog
import com.thecode.aestheticdialogs.components.sheet.models.SheetDialogUiModel
import com.thecode.aestheticdialogs.foundation.AestheticDialogsTheme
import com.thecode.aestheticdialogs.foundation.DialogTone
import com.thecode.aestheticdialogs.model.DialogAction
import com.thecode.aestheticdialogs.model.DialogActionEmphasis
import com.thecode.aestheticdialogs.tokens.AestheticSpacing
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode

/**
 * Renders the images the README shows.
 *
 * These are documentation assets, not baselines. They live here rather than in a
 * screen-recording workflow because a README screenshot that is produced by hand
 * is stale the day after it is taken: this one is regenerated by the same command
 * that records the visual baselines, so a padding change or a palette change
 * shows up in the documentation without anybody remembering to retake anything.
 *
 * ```
 * ./gradlew :aestheticdialogs:recordRoborazziDebug
 * ```
 *
 * Dialogs are captured as whole screens, because a dialog is a window over a
 * scrim and cropping it to the surface would hide half of what the component
 * does. Banners are captured as nodes, because they are ordinary composables and
 * a full screen of empty canvas around them shows nothing.
 */
@RunWith(AndroidJUnit4::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@Config(qualifiers = "w411dp-h700dp-xhdpi")
@OptIn(ExperimentalRoborazziApi::class)
class DocsGalleryTest {

    @get:Rule
    val composeRule = createComposeRule()

    // --- Dialogs ---------------------------------------------------------------

    @Test
    fun confirmationDefault() = screen("confirmation-default") {
        AestheticConfirmationDialog(
            uiModel = ConfirmationDialogUiModel.Default(
                title = "Leave without saving?",
                message = "Your draft has unsaved changes.",
                confirmLabel = "Leave",
                cancelLabel = "Keep editing",
            ),
            onConfirm = {},
            onCancel = {},
            onDismiss = {},
        )
    }

    @Test
    fun confirmationDestructive() = screen("confirmation-destructive") {
        AestheticConfirmationDialog(
            uiModel = ConfirmationDialogUiModel.Destructive(
                title = "Delete this album?",
                message = "The 24 photos inside it will be deleted too. This cannot be undone.",
                confirmLabel = "Delete album",
                cancelLabel = "Keep it",
            ),
            onConfirm = {},
            onCancel = {},
            onDismiss = {},
        )
    }

    @Test
    fun confirmationLoading() = screen("confirmation-loading") {
        AestheticConfirmationDialog(
            uiModel = ConfirmationDialogUiModel.Destructive(
                title = "Delete this album?",
                message = "The 24 photos inside it will be deleted too. This cannot be undone.",
                confirmLabel = "Delete album",
                cancelLabel = "Keep it",
                isConfirming = true,
            ),
            onConfirm = {},
            onCancel = {},
            onDismiss = {},
        )
    }

    @Test
    fun alertDefault() = screen("alert-default") {
        AestheticAlertDialog(
            uiModel = AlertDialogUiModel.Default(
                title = "You are offline",
                message = "We will sync your changes as soon as you reconnect.",
                tone = DialogTone.Warning,
                primaryAction = DialogAction("Retry"),
                secondaryAction = DialogAction("Dismiss", DialogActionEmphasis.Text),
            ),
            onPrimaryAction = {},
            onDismiss = {},
        )
    }

    @Test
    fun alertError() = screen("alert-error") {
        AestheticAlertDialog(
            uiModel = AlertDialogUiModel.Default(
                title = "Upload failed",
                message = "The connection dropped after 12 of 24 photos.",
                tone = DialogTone.Error,
                primaryAction = DialogAction("Retry"),
                secondaryAction = DialogAction("Cancel", DialogActionEmphasis.Secondary),
            ),
            onPrimaryAction = {},
            onDismiss = {},
        )
    }

    @Test
    fun alertDark() = screen("alert-error-dark", dark = true) {
        AestheticAlertDialog(
            uiModel = AlertDialogUiModel.Default(
                title = "Upload failed",
                message = "The connection dropped after 12 of 24 photos.",
                tone = DialogTone.Error,
                primaryAction = DialogAction("Retry"),
                secondaryAction = DialogAction("Cancel", DialogActionEmphasis.Secondary),
            ),
            onPrimaryAction = {},
            onDismiss = {},
        )
    }

    @Test
    fun selectionSingle() = screen("selection-single") {
        AestheticSelectionDialog(
            uiModel = SelectionDialogUiModel.Single(
                title = "Default account",
                items = ACCOUNTS,
                selectedId = "personal",
                cancelLabel = "Cancel",
                confirmLabel = "Use this one",
            ),
            onItemClick = {},
            onCancel = {},
        )
    }

    @Test
    fun selectionMultiple() = screen("selection-multiple") {
        AestheticSelectionDialog(
            uiModel = SelectionDialogUiModel.Multiple(
                title = "Notify me about",
                items = TOPICS,
                selectedIds = setOf("mentions", "releases"),
                confirmLabel = "Save",
                cancelLabel = "Cancel",
                searchQuery = "",
            ),
            onItemClick = {},
            onCancel = {},
        )
    }

    @Test
    fun selectionMultipleDark() = screen("selection-multiple-dark", dark = true) {
        AestheticSelectionDialog(
            uiModel = SelectionDialogUiModel.Multiple(
                title = "Notify me about",
                items = TOPICS,
                selectedIds = setOf("mentions", "releases"),
                confirmLabel = "Save",
                cancelLabel = "Cancel",
                searchQuery = "",
            ),
            onItemClick = {},
            onCancel = {},
        )
    }

    @Test
    fun inputText() = screen("input-text") {
        AestheticInputDialog(
            uiModel = InputDialogUiModel.Text(
                title = "Rename album",
                value = "Kinshasa, 2024",
                label = "Album name",
                confirmLabel = "Rename",
                cancelLabel = "Cancel",
            ),
            onValueChange = {},
            onConfirm = {},
            onCancel = {},
        )
    }

    @Test
    fun inputError() = screen("input-error") {
        AestheticInputDialog(
            uiModel = InputDialogUiModel.Text(
                title = "Add a recipient",
                value = "not-an-address",
                label = "Email",
                errorText = "That does not look like an email address.",
                confirmLabel = "Add",
                cancelLabel = "Cancel",
                isConfirmEnabled = false,
            ),
            onValueChange = {},
            onConfirm = {},
            onCancel = {},
        )
    }

    @Test
    fun inputPassword() = screen("input-password") {
        AestheticInputDialog(
            uiModel = InputDialogUiModel.Password(
                title = "Confirm it is you",
                message = "Enter your password to remove this device.",
                value = "correct horse",
                label = "Password",
                confirmLabel = "Remove device",
                cancelLabel = "Cancel",
            ),
            onValueChange = {},
            onConfirm = {},
            onCancel = {},
        )
    }

    @Test
    fun contentRich() = screen("content-rich") {
        AestheticContentDialog(
            uiModel = ContentDialogUiModel.Default(
                title = "Before you continue",
                subtitle = "Two things worth knowing",
                primaryAction = DialogAction("I agree"),
                secondaryAction = DialogAction("Not now", DialogActionEmphasis.Text),
            ),
            onDismiss = {},
        ) {
            ConsentPlaceholder()
        }
    }

    @Test
    fun feedbackDefault() = screen("feedback-default") {
        AestheticFeedbackDialog(
            uiModel = FeedbackDialogUiModel.Default(
                title = "Album archived",
                message = "You will find it under Archived in Settings.",
                tone = DialogTone.Info,
                actionLabel = "Got it",
            ),
            onDismiss = {},
        )
    }

    @Test
    fun feedbackDefaultNeutral() = screen("feedback-default-neutral") {
        AestheticFeedbackDialog(
            uiModel = FeedbackDialogUiModel.Default(
                title = "Album archived",
                message = "You will find it under Archived in Settings.",
                tone = DialogTone.Neutral,
                actionLabel = "Got it",
            ),
            onDismiss = {},
        )
    }

    @Test
    fun feedbackGradient() = screen("feedback-gradient") {
        AestheticFeedbackDialog(
            uiModel = FeedbackDialogUiModel.Gradient(
                title = "Message sent",
                message = "It will arrive even if you close the app.",
                tone = DialogTone.Success,
                actionLabel = "Nice",
            ),
            onDismiss = {},
        )
    }

    @Test
    fun feedbackGradientError() = screen("feedback-gradient-error") {
        AestheticFeedbackDialog(
            uiModel = FeedbackDialogUiModel.Gradient(
                title = "Payment declined",
                message = "Your bank refused the charge. Nothing was taken.",
                tone = DialogTone.Error,
                actionLabel = "Try another card",
            ),
            onDismiss = {},
        )
    }

    @Test
    fun feedbackCompact() = screen("feedback-compact") {
        AestheticFeedbackDialog(
            uiModel = FeedbackDialogUiModel.Compact(
                title = "Album archived",
                tone = DialogTone.Success,
                actionLabel = "Undo",
            ),
            onDismiss = {},
        )
    }

    @Test
    fun sheetDefault() = screen("sheet-default") {
        AestheticSheetDialog(
            uiModel = SheetDialogUiModel.Default(
                title = "Share this album",
                message = "Anyone with the link can see the 24 photos inside it.",
                primaryAction = DialogAction("Copy link"),
                secondaryAction = DialogAction("Cancel", DialogActionEmphasis.Text),
            ),
            onDismiss = {},
        )
    }

    @Test
    fun headerDefault() = screen("header-default") {
        AestheticHeaderDialog(
            uiModel = HeaderDialogUiModel.Default(
                title = "Albums, offline",
                message = "Everything you starred is on the device now.",
                primaryAction = DialogAction("Take the tour"),
                secondaryAction = DialogAction("Later", DialogActionEmphasis.Text),
            ),
            onPrimaryAction = {},
            onDismiss = {},
        )
    }

    @Test
    fun progressDefault() = screen("progress-default") {
        AestheticProgressDialog(
            uiModel = ProgressDialogUiModel.Default(
                title = "Signing you in",
                message = "This takes a moment on a slow connection.",
            ),
        )
    }

    @Test
    fun progressDeterminate() = screen("progress-determinate") {
        AestheticProgressDialog(
            uiModel = ProgressDialogUiModel.Determinate(
                title = "Uploading",
                message = "Keep the app open until this finishes.",
                progress = 0.5f,
                progressLabel = "12 of 24",
                tone = DialogTone.Info,
                cancelLabel = "Cancel upload",
            ),
            onCancel = {},
        )
    }

    // --- Banners ---------------------------------------------------------------

    @Test
    fun notificationDefault() = banner("notification-default") {
        NotificationUiModel.Default(
            title = "Saved",
            message = "Your changes are on every device.",
            tone = DialogTone.Success,
        )
    }

    @Test
    fun notificationFilled() = banner("notification-filled") {
        NotificationUiModel.Filled(
            title = "Heads up",
            message = "Two invoices are due this week.",
            tone = DialogTone.Warning,
        )
    }

    @Test
    fun notificationAmbient() = banner("notification-ambient") {
        NotificationUiModel.Ambient(
            title = "Back online",
            message = "Syncing what you missed.",
            tone = DialogTone.Success,
        )
    }

    @Test
    fun notificationAmbientLongCopy() = banner("notification-ambient-long") {
        NotificationUiModel.Ambient(
            title = "Reconnected to the office network after a long outage",
            message = "Syncing the twenty-four items that changed while you were away.",
            tone = DialogTone.Info,
        )
    }

    @Test
    fun notificationEmoji() = banner("notification-emoji") {
        NotificationUiModel.Default(
            title = "Nice one",
            message = "That was your tenth album this month.",
            tone = DialogTone.Success,
            emoji = "\uD83D\uDC4D",
        )
    }

    @Test
    fun notificationGradient() = banner("notification-gradient") {
        NotificationUiModel.Gradient(
            title = "Amara sent a photo",
            message = "Tap to open the album",
            timestamp = "13:56",
            tone = DialogTone.Info,
        )
    }

    @Test
    fun notificationAction() = banner("notification-action") {
        NotificationUiModel.Default(
            title = "Album archived",
            message = "24 photos moved out of your library.",
            tone = DialogTone.Neutral,
            action = NotificationAction("Undo"),
        )
    }

    @Test
    fun notificationProgress() = banner("notification-progress") {
        NotificationUiModel.Default(
            title = "Uploading 12 of 24",
            message = "You can keep using the app.",
            tone = DialogTone.Info,
            progress = 0.5f,
        )
    }

    @Test
    fun notificationPresence() = banner("notification-presence") {
        NotificationUiModel.Gradient(
            title = "Amara sent a photo",
            message = "Tap to open the album",
            tone = DialogTone.Info,
            timestamp = "13:56",
            presence = NotificationPresence.Online,
        )
    }

    @Test
    fun notificationStrip() = banner("notification-strip") {
        NotificationUiModel.Strip(
            title = "You are offline",
            message = "Showing the last version we downloaded.",
        )
    }

    @Test
    fun notificationsDark() {
        composeRule.setContent {
            AestheticDialogsTheme(darkTheme = true) {
                BannerStage {
                    Column(verticalArrangement = Arrangement.spacedBy(AestheticSpacing.lg)) {
                        AestheticNotification(
                            uiModel = NotificationUiModel.Default(
                                title = "Saved",
                                message = "Your changes are on every device.",
                                tone = DialogTone.Success,
                            ),
                            onDismiss = {},
                        )
                        AestheticNotification(
                            uiModel = NotificationUiModel.Filled(
                                title = "Heads up",
                                message = "Two invoices are due this week.",
                                tone = DialogTone.Warning,
                            ),
                            onDismiss = {},
                        )
                        AestheticNotification(
                            uiModel = NotificationUiModel.Ambient(
                                title = "Back online",
                                message = "Syncing what you missed.",
                                tone = DialogTone.Success,
                            ),
                            onDismiss = {},
                        )
                    }
                }
            }
        }
        captureStage("notifications-dark")
    }

    // --- Plumbing --------------------------------------------------------------

    private fun screen(name: String, dark: Boolean = false, content: @Composable () -> Unit) {
        composeRule.setContent {
            AestheticDialogsTheme(darkTheme = dark) {
                Box(
                    modifier = Modifier
                        .fillMaxSize()
                        .background(AestheticDialogsTheme.colors.surface.sunken),
                ) {
                    HostAppBackdrop()
                    content()
                }
            }
        }
        captureScreenRoboImage("$DOCS_IMAGES/$name.png", HALF_SCALE)
    }

    private fun banner(name: String, uiModel: @Composable () -> NotificationUiModel) {
        composeRule.setContent {
            AestheticDialogsTheme(darkTheme = false) {
                BannerStage {
                    AestheticNotification(uiModel = uiModel(), onDismiss = {})
                }
            }
        }
        captureStage(name)
    }

    private fun captureStage(name: String) {
        composeRule.onNodeWithTag(STAGE_TAG)
            .captureRoboImage("$DOCS_IMAGES/$name.png", HALF_SCALE)
    }

    /**
     * The frame a banner is photographed in: the theme canvas plus one gutter of
     * padding, so the shadow is not clipped at the edge of the image.
     */
    @Composable
    private fun BannerStage(content: @Composable () -> Unit) {
        Box(
            modifier = Modifier
                .testTag(STAGE_TAG)
                .width(BANNER_STAGE_WIDTH)
                .wrapContentHeight()
                .background(AestheticDialogsTheme.colors.surface.sunken)
                .padding(AestheticSpacing.xl),
            contentAlignment = Alignment.Center,
        ) {
            content()
        }
    }

    /**
     * Undecorated blocks standing in for the application behind the dialog.
     *
     * A dialog photographed on an empty canvas hides the two things the frame is
     * responsible for — the scrim and the elevation — so the gallery puts
     * something behind it. It is deliberately abstract: an invented app screen
     * would say more about the screenshot than about the library.
     */
    @Composable
    private fun HostAppBackdrop() {
        val colors = AestheticDialogsTheme.colors
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(AestheticSpacing.xl),
            verticalArrangement = Arrangement.spacedBy(AestheticSpacing.lg),
        ) {
            Box(
                Modifier
                    .width(BACKDROP_TITLE_WIDTH)
                    .height(BACKDROP_TITLE_HEIGHT)
                    .background(colors.border.default, RoundedCornerShape(AestheticSpacing.sm)),
            )
            Spacer(Modifier.height(AestheticSpacing.sm))
            repeat(BACKDROP_ROWS) {
                Box(
                    Modifier
                        .fillMaxWidth()
                        .height(BACKDROP_ROW_HEIGHT)
                        .background(colors.border.subtle, RoundedCornerShape(AestheticSpacing.md)),
                )
            }
        }
    }

    /** Placeholder body for the rich-content dialog gallery entry. */
    @Composable
    private fun ConsentPlaceholder() {
        val colors = AestheticDialogsTheme.colors
        // The content dialog hands over an unpadded column on purpose, so the
        // gallery pads like any other caller. Rendering it flush to the surface
        // is what made the screenshot look misaligned against the header.
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = AestheticSpacing.xxl),
            verticalArrangement = Arrangement.spacedBy(AestheticSpacing.md),
        ) {
            CONSENT_LINES.forEach { line ->
                Text(
                    text = line,
                    style = AestheticDialogsTheme.typography.message,
                    color = colors.content.secondary,
                )
            }
        }
    }

    private companion object {
        // Relative to the module directory, which is where Roborazzi resolves
        // output paths from.
        const val DOCS_IMAGES = "../docs/images"
        const val STAGE_TAG = "gallery-stage"

        val HALF_SCALE = RoborazziOptions(
            recordOptions = RoborazziOptions.RecordOptions(resizeScale = 0.5),
        )

        val BANNER_STAGE_WIDTH = 420.dp
        val BACKDROP_TITLE_WIDTH = 180.dp
        val BACKDROP_TITLE_HEIGHT = 28.dp
        val BACKDROP_ROW_HEIGHT = 72.dp
        const val BACKDROP_ROWS = 6

        val ACCOUNTS = listOf(
            SelectionItem("personal", "Personal", "amara@example.com"),
            SelectionItem("work", "Work", "a.diallo@company.com"),
            SelectionItem("shared", "Shared", "Read only", enabled = false),
        )

        val TOPICS = listOf(
            SelectionItem("mentions", "Mentions", "When someone tags you"),
            SelectionItem("releases", "Releases", "New versions of apps you follow"),
            SelectionItem("digest", "Weekly digest", "Every Monday morning"),
            SelectionItem("beta", "Beta programme", "Not available in your region", enabled = false),
        )

        val CONSENT_LINES = listOf(
            "Albums stay on your device and are encrypted before they leave it.",
            "You can revoke access at any time from Settings.",
            "Nothing here is used to train anything.",
        )
    }
}
